### ISSUE TITLE
HTTP REST API

### ISSUE THREAD

**Issue by adamkrellenstein** [CounterpartyXCP/counterpartyd#566]
Copy Bitcoin Core's: https://github.com/bitcoin/bitcoin/pull/2844

**Comment by Millz0r** [comment]
The API is almost complete, it just needs few clarifications:

1. There is a problem making rest at /. The problem is with URL routing in Flask, in order to get a / match you would need to match all URLs (including API) and then send it it's way (so /API/ would also be served from that). I don't think it's a good idea to couple things like that - I think it would be better to keep API at /api/ (although atm it also listens to /, maybe we should add a info page at / saying you should either poll /api/ or /rest/?) and keep REST at /rest/.

2. Mapping URL arguments to get_rows one. get_rows has a lot of arguments, such as filters, filter operators, order, etc. Do we want to support all of them? At the moment I have only seen simplest examples like this:
/rest/balances/address/349sdn84j3b5s9djh4983
As I understand that should resolve to SQL query:
SELECT * FROM balances WHERE address=349sdn84j3b5s9djh4983
Do we want to keep it like that (only WHERE statement match for URLs) or do we want to upgrade to more functionality?
Personally I think we can start with the simple approach, once we release this and get some feedback from people actually using it we might consider extending it.

**Comment by ouziel-slama** [comment]
1. Can you do something like this ?
```
@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def catch_all(path):
    if path == '' or path.split('/')[0] == 'api':
        return rpc_query(path)
    else:
        return rest_query(path)
```

2. Yeah, I agree. The `op` operator (OR or AND), seems enough to me for a start.

**Comment by Millz0r** [comment]
1. Yip, I'll do it like that.

2. How would the operator be described - between queries, eg.?
```
/rest/balances/address/349sdn84j3b5s9djh4983/OR/asset/BTC/AND/quantity/2
```
This would be slightly more problematic with current code, but it is doable.

**Comment by ouziel-slama** [comment]
The `op` parameter is for all field/value in the query, you just need it once, for instance like this: 
```
/balances/address/349sdn84j3b5s9djh4983/asset/BTC/quantity/2?op=1
```
